### ISSUE TITLE
Please tag releases in git

### ISSUE THREAD

**Issue by rrthomas** [gjwgit/wajig#13]
The tags, never mind the releases, for this project, are rather partial: the latest tag is 4.0.2, also the only tag in the 4.x series. This is confusing. It would be ideal if you could tag all the releases; next best would at least be to tag the latest and update your `Makefile` to tag from now on; failing that, removing all the tags from git would at least reduce confusion.

**Comment by gjwgit** [comment]
Good point @rrthomas . I need to be more thorough with the tags. Do you have a suggestion of how to automate that (otherwise it is haphazard as you note). I'll check too.

**Comment by rrthomas** [comment]
On many of my projects, I simply have a `release` target in a Makefile that runs `git tag` and `git push --tags`.

**Comment by gjwgit** [comment]
Great. Thanks for the example. I'll add that into the workflow.

**Comment by gjwgit** [comment]
Added to workflow. Tags will be added going forward. Closing this issue now.
