### ISSUE TITLE
Can't install wajig as user in Debian 12

### ISSUE THREAD

**Issue by rrthomas** [gjwgit/wajig#16]
In Debian 12 (bookworm), the shipped wajig 4.0.3 does not work (and in Debian 11 it's not available anyway).

Also in Debian 12, `pip install --user` is not available, so the user installation instructions in `README.rst` do not work. The best alternative seems to be pipx, but that installs Python apps in venvs, so all the deps have to be installed. However, apt is not installed, and cannot easily be, since there's no PyPI package for it (as far as I can see). This isn't exactly a wajig problem, but it is a problem for wajig!

**Comment by rrthomas** [comment]
I have come up with a workaround, which is not great, but here it is: having installed wajig with pipx, symlink the following into its venv:

```
ln -s /usr/lib/python3/dist-packages/apt
ln -s /usr/lib/python3/dist-packages/apt_pkg.cpython-*.so
ln -s /usr/lib/python3/dist-packages/apt_pkg-stubs
```

**Comment by gjwgit** [comment]
Thanks @rrthomas. I'll explore how best this can be done. Pull Requests are very welcome.

**Comment by gjwgit** [comment]
Hi @rrthomas, testing on a fresh Debian 12 on Linode

```
# apt update
# apt upgrade 
# apt install wajig
```

```
$ wajig --version
wajig 4.0.3
$ wajig update
$ wajig distupgrade
$ wajig install most
```
Seems to work for me. 

Is it still not working for you?

**Comment by rrthomas** [comment]
You're quite right that wajig does work in Debian 12 out of the box. I have retitled the bug; it's still going to be useful to install wajig as a user to get a newer version for bug fixes/new features.

**Comment by gjwgit** [comment]
Certainly, and I do just that. I think I'm okay (with the newest Debian/Ubuntu) to use `--break-system-packages` with `pip`. I've not quite got on top of `pipx` yet, and as I am installing as a user I am guessing this does not actually break system packages.

```
pip install wajig --break-system-pacakges
```

The `--user` was dropped from `README.rst` already.

**Comment by rrthomas** [comment]
I didn't know about `--break-system-packages`, that's the magic override I needed, thanks!
