### ISSUE TITLE
New apt shows upgrade packages and requires prompt

### ISSUE THREAD

**Issue by eddelbuettel** [gjwgit/wajig#22]
On my Ubuntu 24.10 laptop (and also newer Debian-based containers), `wajig` now requires more interaction.  My 'go-to' `wajig update; wajig new` and then ~`wajig update`~ `wajig upgrade` (edited).  That last command now requires a 'yes' answer to the new prompt that `apt` display.  Which I find both useful but maybe also want to override?  Maybe a new command is best...

I tried a quick local build with an added `--yes` but that didn't seem to work; my machine then upgraded when I used `wajig dist-upgrade`.  I will try another go in a day or two when I have new packages.

As an aside, there is also command-line noise now when installing (and I called the local build 4.1.2.1 to set it apart):

```
[... in a container running Debian testing/unstable ...]
Setting up wajig (4.1.2.1) ...
/usr/lib/python3/dist-packages/wajig/commands.py:621: SyntaxWarning: invalid escape sequence '\.'
  ", $6, $7, $8}' | sed 's|\.000000000||'")
/usr/lib/python3/dist-packages/wajig/commands.py:653: SyntaxWarning: invalid escape sequence '\.'
  "grep -E -v '(\.1|\.1\.gz|\.8|\.8\.gz|README)$'")
/usr/lib/python3/dist-packages/wajig/commands.py:1049: SyntaxWarning: invalid escape sequence '\*'
  command  = 'for SRC in `find /etc/apt/ -name \*.list`; do '
/usr/lib/python3/dist-packages/wajig/commands.py:1050: SyntaxWarning: invalid escape sequence '\-'
  command += 'grep -o "^deb https://ppa.launchpad.net/[a-z0-9\-]\+/[a-z0-9\-]\+" $SRC; done | '
/usr/lib/python3/dist-packages/wajig/commands.py:1124: SyntaxWarning: invalid escape sequence '\|'
  "\|".join(args.patterns))
/usr/lib/python3/dist-packages/wajig/commands.py:1188: SyntaxWarning: invalid escape sequence '\['
  regexp = set('.^$*+?{},\[]|()')
/usr/lib/python3/dist-packages/wajig/commands.py:1256: SyntaxWarning: invalid escape sequence '\]'
  command += 'cut -d "=" -f2 | tr -d "\]"); '
/usr/lib/python3/dist-packages/wajig/util.py:492: SyntaxWarning: invalid escape sequence '\('
  command = command + "grep '^\($"
/usr/lib/python3/dist-packages/wajig/util.py:494: SyntaxWarning: invalid escape sequence '\|'
  command = command + " \|" + i
/usr/lib/python3/dist-packages/wajig/util.py:495: SyntaxWarning: invalid escape sequence '\)'
  command = command + " \)' |"
Processing triggers for libc-bin (2.40-3) ...
root@720cda39b5be:/work# 
```

PS Oh I see that #19 seems to address this last bit.

**Comment by eddelbuettel** [comment]
Follow-up:  Debian testing does it too, and I actually run into this more often on it. It just hit me again on `wajig distupgrade`.

**Comment by gjwgit** [comment]
Not seeing it on my 24.10 with 

```
$ apt --version
apt 2.9.8 (amd64)
```

I'll investigate further on a fresh install.

**Comment by eddelbuettel** [comment]
Weird. It definitely is happening for me on 24.10. Shall I do a 'animated gif' or mp4 movie?

**Comment by gjwgit** [comment]
It would be great to see the behaviour and debug why I don't see it. Thanks.

**Comment by gjwgit** [comment]
Did you mean `wajig upgrade` rather then `wajig update` in your first description. That makes more sense and `yes`

**Comment by eddelbuettel** [comment]
Yes. It happens with `wajig update; wajig upgrade` during the upgrade call.  See [this link for demo](https://github.com/eddelbuettel/images/blob/master/2024-12-02/wajig_apt_prompt_2024-12-02_16-08.gif)

**Comment by eddelbuettel** [comment]
On the Debian testing box, running

```sh
wajig update
wajig new
sudo apt upgrade --yes
```

worked as expected.  My local patch did, I think, add `--yes` here to yield `"/usr/bin/apt-get {} {} {} --yes --show-upgraded --with-new-pkgs upgrade"` and as I recall that did not work and still yielded a prompt.  I will try that tomorrow 'by hand'.

**Comment by eddelbuettel** [comment]
On Ubuntu 24.10, running `sudo apt --yes --show-upgraded --with-new-pkgs upgrade` also works.  The line is from my local repo, I may have had a different one in the local .deb I built earlier.

**Comment by gjwgit** [comment]
Thanks for the extra information Dirk. 

Just to ensure I am understanding, when you run `wajig distupgrade --yes` it is now asking `[Y/n]`.

I don't seem to see that behvaiour and I do see the nice new apt output (i.e., the new update of apt).

I run `(wajig update; wajig distupgrade --yes)` daily as a cron job and I don't get any question. 

My log file from this morning is:

```
...
Fetched 565 kB in 2s (251 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
3 packages can be upgraded. Run 'apt list --upgradable' to see them.
This is the same as the previous count with 0 new packages.
There are 2 new upgrades

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
Upgrading:
  firmware-sof-signed

Not upgrading yet due to phasing:
  alsa-ucm-conf

Not upgrading:
  libcanberra-pulse

Summary:
  Upgrading: 1, Installing: 0, Removing: 0, Not Upgrading: 2
  Download size: 7,083 kB
  Space needed: 169 kB / 214 GB available

Get:1 http://au.archive.ubuntu.com/ubuntu oracular-updates/main amd64 firmware-sof-signed all 2024.06-1ubuntu1.1 [7,083 kB]
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: Inappropriate ioctl for device
Fetched 7,083 kB in 6s (1,273 kB/s)
(Reading database ... 687146 files and directories currently installed.)
Preparing to unpack .../firmware-sof-signed_2024.06-1ubuntu1.1_all.deb ...
Unpacking firmware-sof-signed (2024.06-1ubuntu1.1) over (2024.06-1ubuntu1) ...
Setting up firmware-sof-signed (2024.06-1ubuntu1.1) ...
```

**Comment by eddelbuettel** [comment]
`upgrade`, not `dist-upgrade` as written multiple times above and demonstrated in the gif video.

**Comment by gjwgit** [comment]
Oops - my bad reading. I'll look again. Thanks for clarifying.

**Comment by gjwgit** [comment]
`wajig update` is now utilising `apt` directly with `--yes` hard coded. Version 4.1.3.

Thanks for the issue and guidance @eddelbuettel.

**Comment by eddelbuettel** [comment]
Awesome!

I found another micro bug in the .deb package in that the man page does not get installed but we can leave that for another time.  I'll roll up 4.1.3 to Debian.

**Comment by eddelbuettel** [comment]
Oh and SAFEUPGRADE looks useful -- I saw those 'phased upgrade' but didn't know what I should do there. Nice.

**Comment by eddelbuettel** [comment]
My muscle memory seems to flip between `upgrade` and `dist-upgrade`.  The former is _great_ now, thanks very much.  Do we need the same for `dist-upgrade` too?

PS Or maybe not?  Maybe it always asked for a key press there even under older apt?  Hm.
