### ISSUE TITLE
wajig doc | most    issue 

### ISSUE THREAD

**Issue by OrionRandD** [gjwgit/wajig#4]
wajig doc| most

Traceback (most recent call last):
  File "/usr/bin/wajig", line 33, in <module>
    sys.exit(load_entry_point('wajig==4.0.3', 'console_scripts',
'wajig')())
  File "/usr/lib/python3/dist-packages/wajig/__init__.py", line 1209, in main
    result.func(result)
  File "/usr/lib/python3/dist-packages/wajig/commands.py", line 1273, in tutorial
    teach=args.teach, noop=args.noop)
AttributeError: 'Namespace' object has no attribute 'teach'

How can I fix this error?

**Comment by gjwgit** [comment]
Thanks for the report - Seems to have broken. We'll have a look.

**Comment by gjwgit** [comment]
Fixed in 4.0.5

**Comment by OrionRandD** [comment]
On Sat, Mar 26, 2022 at 03:57:26AM -0700, gjwgit wrote:

------------------------

Hi,
I have installed wajig with pip, but it did not install the TUTORIAL.gz 
See here:

$ wajig --version
wajig 4.0.5
-> ***@***.*** 07:57:19
~ $ wajig --help
usage: wajig [-h] [-V] [<command> [--help] [--teach] [--noop] [<options>]]

Unified package management front-end for Debian/Ubuntu.

optional arguments:
  -h, --help     show this help message and exit
  -V, --version  show wajig version

'wajig commands' to display available commands.
'wajig <command> --help' for command sepcific help.
'wajig doc | most' to display a tutorial.

See what's happening with --teach or --noop.

Please direct queries to https://stackoverflow.com/ and tag as wajig.
-> ***@***.*** 07:57:33
~ $ wajig doc | most
gzip: /usr/share/doc/wajig/TUTORIAL.gz: No such file or directory

Do I have to install the TUTORIAL.gz by hand? If so, where do I get it?

------------------------

**Comment by QBANIN** [comment]
sudo wajig list-hold                                                                                    ─╯
Traceback (most recent call last):
  File "/usr/bin/wajig", line 33, in <module>
    sys.exit(load_entry_point('wajig==4.0.10', 'console_scripts', 'wajig')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/wajig/__init__.py", line 1212, in main
    result.func(result)
  File "/usr/lib/python3/dist-packages/wajig/commands.py", line 632, in listhold
    perform.execute("dpkg --get-selections | grep -E 'hold$' | cut -f1", teach=args.teach, noop=args.noop)
                                                                               ^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'teach'

**Comment by gjwgit** [comment]
Thanks for the report (would be better as a separate issue though).

Fixed in wajig 4.0.12

https://pypi.org/project/wajig/4.0.12/

https://github.com/gjwgit/wajig/commit/bc11bb75c319920c81dc489b0b9271409f9bae26
