### ISSUE TITLE
wajig update --teach (--noop) issue

### ISSUE THREAD

**Issue by OrionRandD** [gjwgit/wajig#5]
Also wajig update --teach (--noop) 
are not working. They do not show the underline apt commands  :(

**Comment by gjwgit** [comment]
Thanks. Looking into it.

**Comment by gjwgit** [comment]
Fixed in 4.0.5

**Comment by OrionRandD** [comment]
> Fixed in 4.0.5

Thx. 
My version is still 4.0.3 
Debian repo will take a time to upgrade to the new version...

**Comment by gjwgit** [comment]
Yes. In the meantime to install 4.0.5:

$ pip install wajig

**Comment by OrionRandD** [comment]
Oh. Thx a lot...
