### ISSUE TITLE
New upload to Debian?   Also bash completion issue

### ISSUE THREAD

**Issue by eddelbuettel** [gjwgit/wajig#7]
On Ubuntu 22.04 I noticed that bash completion does not currently work, the appropriate file is only in `/usr/lib/python3/dist-packages/wajig/bash_completion.d/` and needs a manual copy (or link) to `/etc/bash_completion.d/`.

Looking at the repo I see you are at 4.0.5.  Shall we coordinate another Debian build and update?

**Comment by rrthomas** [comment]
I'm running 4.0.5 installed from source, as the version shipped with Ubuntu 22.04 crashes on startup; similarly, I've recently had to find other incantations for Debian 11 systems, where wajig unfortunately isn't shipped at all.

I see that wajig will be in bookworm, which is progress, but it would be great if it could be updated in sid, as it's still on 4.0.3 in both places.

**Comment by gjwgit** [comment]
Thanks for pointing that out. I'll get it updated.

Regards,
Graham

**Comment by gjwgit** [comment]
@rrthomas Testing fresh Ubuntu 22.04 and fresh apt install of wajig 4.0.3. That is working just fine for me.

Currently working on getting an update ready for a Debian build.

**Comment by gjwgit** [comment]
Testing deb build of wajig v4.0.12:

Fresh Ubuntu 23.04 on Linode: 

```
apt update
apt upgrade
apt install python3-levenshtein python3-thefuzz aptitude
dpkg --install wajig_4.0.12_all.deb 
wajig
wajig --version
wajig install most
```

**Comment by eddelbuettel** [comment]
Not novel; been running on 22.04 then 22.10 then 23.04.

But do look at open bugs etc at 
- debian https://bugs.debian.org/cgi-bin/pkgreport.cgi?src=wajig
- ubuntu https://bugs.launchpad.net/ubuntu/+source/wajig

(Now, I am myself not leading by example in clearing mine but hey I may update my repos more often than you... :wink: )

**Comment by gjwgit** [comment]
Thanks Dirk. Likewise.

Will check the open bugs too. Thanks for the reminder.

**Comment by gjwgit** [comment]
Hi Dirk - great to know you still use wajig. Thanks.  I (and my team) are daily users too :-) 

I've checked through all Debian and Ubuntu bug reports. A couple of good feature requests remain but all else has been addressed.

May we coordinate another Debian build and update?

I've tested the github version

**Comment by eddelbuettel** [comment]
Yes if you can wrap a new version with the proper love and care I can surely look into build and upload.

**Comment by gjwgit** [comment]
Thanks. 

With proper love and care (checked everything I have documented and could think of) this is ready to build and upload. 

Tested again on a fresh Debian 12:

```
$ uname -a
Linux localhost 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux
```

No errors or warnings:

```
$ git clone git@github.com:gjwgit/wajig.git
$ cd wajig
$ sudo apt install build-essential dh-python python3-setuptools python3-thefuzz python3-all debhelper-compat
$ make deb
$ sudo apt install python3-distro python3-levenshtein aptitude
$ sudo dpkg --install wajig_4.0.12_all.deb
$ wajig version
$ wajig install most
```

The binary package is available from:

```
$ wget https://access.togaware.com/wajig_4.0.12_all.deb
```

**Comment by eddelbuettel** [comment]
Great. Is there a tar.gz I can use (given the Debian toolchain) to inject into the git repo underlying the package?  Declaring / tagging a GH release would do too.

**Comment by gjwgit** [comment]
There is now a GH release (https://github.com/gjwgit/wajig/releases/tag/v4.0.12), and added this task to my wrap up list of things I must do. Thanks.

**Comment by eddelbuettel** [comment]
Whoops.  My bad.  We apparently used your normal repo and I just build off it -- no repo at salsa.debian.org as I usually do. Sorry for the false alarm.

Built and uploaded based on this repo ie https://github.com/gjwgit/wajig

**Comment by gjwgit** [comment]
Closing - 4.0.12 accepted:  https://packages.qa.debian.org/w/wajig.html
